[package]
name = "shellingo_cli"
version = "0.1.0"
edition = "2021"

[dependencies]
shellingo_core = { path = "../shellingo_core" }
walkdir = "2.5.0"
regex = "1.10.6"
# TUI
ratatui = { version = "0.29.0", features = ["crossterm"] }
strum = "0.26"
strum_macros = "0.26"
