name: Rust

on: workflow_dispatch

env:
  CARGO_TERM_COLOR: always
  CARGO_INCREMENTAL: 0
  
jobs:
  build-nix:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        BUILD_TARGET: [release] # refers to a cargo profile
    outputs:
      release_built: ${{ steps.set-output.outputs.release_built }}
    steps:
      - uses: actions/checkout@v5
      - name: Rust update
        run: rustup update
      - name: Build binaries in "${{ matrix.BUILD_TARGET }}" mode
        run: cargo build --profile ${{ matrix.BUILD_TARGET }}
      - name: Run tests in "${{ matrix.BUILD_TARGET }}" mode
        run: cargo test --profile ${{ matrix.BUILD_TARGET }}
      - name: Upload release artifact
        uses: actions/upload-artifact@v4
        with:
          name: shellingo-linux
          path: target/${{ matrix.BUILD_TARGET }}/shellingo

  build-win:
    runs-on: windows-latest
    strategy:
      matrix:
        BUILD_TARGET: [release] # refers to a cargo profile
    outputs:
      release_built: ${{ steps.set-output.outputs.release_built }}
    steps:
      - uses: actions/checkout@v5
      - name: Rust update
        run: rustup update
      - name: Build binaries in "${{ matrix.BUILD_TARGET }}" mode
        run: cargo build --profile ${{ matrix.BUILD_TARGET }}
      - name: Run tests in "${{ matrix.BUILD_TARGET }}" mode
        run: cargo test --profile ${{ matrix.BUILD_TARGET }}
      - name: Upload release artifact
        uses: actions/upload-artifact@v4
        with:
          name: shellingo-windows
          path: target/${{ matrix.BUILD_TARGET }}/shellingo
